SINGLE INHERITANCE

In [6]:
class SRM:
  def __init__(self, fname, lname):# _init_ = initation
    self.firstname = fname
    self.lastname = lname
  def printname(self):
    print(self.firstname, self.lastname)
x = SRM("lalith", "Kumar")
x.printname()


lalith Kumar


Multiple Inheritance in Python

In [1]:
class MCAGENAI:
	def m(self):
		print("In Class1")

class MCAA(MCAGENAI):
	def m(self):
		print("In MCAA")

class MCAB(MCAGENAI):
	def m(self):
		print("In MCAB")

class MCAC(MCAA, MCAB):
	pass

obj = MCAC()
obj.m()


In MCAA


In [20]:

class Grandfather:

	def __init__(self, grandfathername):
		self.grandfathername = grandfathername
class Father(Grandfather):
	def __init__(self, fathername, grandfathername):
		self.fathername = fathername

		Grandfather.__init__(self, grandfathername)
class Son(Father):
	def __init__(self, sonname, fathername, grandfathername):
		self.sonname = sonname
		Father.__init__(self, fathername, grandfathername)
	def print_name(self):
		print('Grandfather name :', self.grandfathername)
		print("Father name :", self.fathername)
		print("Son name :", self.sonname)
s1 = Son('Prince', 'Rampal', 'Lal mani')
print(s1.grandfathername)
s1.print_name()


Lal mani
Grandfather name : Lal mani
Father name : Rampal
Son name : Prince


FOR LOOP

In [7]:
SRM = ["BCA", "MCA", "MBA"]
for x in SRM:
  print(x)


BCA
MCA
MBA


WHILE LOOP

In [9]:
i = 1
while i < 5:
  print(i)
  i += 1


1
2
3
4


NESTED LOOP

In [19]:
SRM = ["MCA", "BCA"]
LOYOLA = ["Msc", "Bsc"]

for i in SRM:
  for j in LOYOLA:
    print(i, j)

MCA Msc
MCA Bsc
BCA Msc
BCA Bsc


LOCAL VARIABLE

In [39]:
def myfunc():
  x=100
  print(x)
myfunc()




100


In [41]:
a = 60
def myfun():
  b=100
  print(a+b)
myfun()

160


In [54]:
import numpy as np
from numpy import *
arr =np.array([1,2,3.2])
print(arr)
print(arr.dtype)
arr=np.arange(1,4,2)
print(arr)

[1.  2.  3.2]
float64
[1 3]


In [53]:
arr=np.linspace(1,12,3)
print(arr)

[ 1.   6.5 12. ]


In [55]:
arr=np.logspace(1,2,3)
print(arr)

[ 10.         31.6227766 100.       ]


In [59]:
arr=np.logspace(1,10,num=10,base=2)
print(arr)
print(arr[3])


[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
16.0


In [71]:
print(arr[3])

16.0


In [72]:
print('%.2f' %arr[3])

16.00


In [78]:
arr=zeros(10,int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [81]:
arr=ones(10,int)
print(arr)

[1 1 1 1 1 1 1 1 1 1]


In [83]:
arr=ones(11)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [90]:
arr= zeros((3,7),int)
print(arr)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [91]:
arr= zeros((3,5,7),int)
print(arr)

[[[0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]]]


In [93]:
arr= ones((3,6,7))
print(arr)

[[[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]]


In [98]:
list = [1,3,5,6,8]
arr= np.array(list)
print(arr)

[1 3 5 6 8]


In [102]:
list=[[1,2],[3,4]]
arr=np.array(list)
print(arr)

[[1 2]
 [3 4]]


In [106]:
matrix=np.full(3,2002)
print(matrix)

[2002 2002 2002]


In [107]:
matrix=np.full((2,3),10)
print(matrix)

[[10 10 10]
 [10 10 10]]


In [108]:

matrix=np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
